version: 0.1

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build:prod
      - aws s3 rm s3://heroeditor.com/ --recursive
      - aws s3 cp dist/ s3://heroeditor.com/ --recursive