version: 0.1

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build:prod
  post-build:
    commands:
      - aws s3 sync dist/ s3://heroeditor.com/ --recursive 